name: topic-ci

on:
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: install
        run: npm i --legacy-peer-deps

      - name: lint
        run: npm run lint

  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: install
        run: npm i --legacy-peer-deps

      - name: build
        run: npm run build
        env:
          BASE_PATH: /

      - name: create .nojekyll
        run: touch .output/public/.nojekyll

      - name: deploy pages
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          # ACCESS_TOKEN: ${{ secrets.DEMO_REPO_ACCESS_TOKEN }}
          branch: gh-pages
          folder: .output/public
          # repository-name: zodiac-G12/demo
